/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brandNavy: '#071B3A',
        brandRoyalBlue: '#1455A0',
        brandGreen: '#168B45',
        brandGold: '#F4C542',
        brandWarmGold: '#DFAE2B',
        brandLightBlue: '#EEF5FF',
        brandLightGreen: '#EFFAF3',
        brandBg: '#F9F9FF',
        brand: {
          navy: '#071B3A',
          gold: '#F4C542',
          green: '#168B45',
          light: '#F4F8FC',
          text: '#101828',
          muted: '#667085',
          navyLight: '#0d2b59',
          goldHover: '#e0b332',
          greenHover: '#127439',
        },
        'primary-container': '#071B3A',
        'tertiary-fixed': '#F4C542',
        'tertiary-fixed-dim': '#efc13e',
        'secondary': '#006d33',
        'secondary-container': '#8cf6a3',
        'secondary-fixed': '#8ff9a6',
        'background': '#f9f9ff',
        'surface': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e0e8ff',
        'surface-container-highest': '#dbe2f9',
        'surface-variant': '#dbe2f9',
        'on-surface': '#141b2c',
        'on-surface-variant': '#44474e',
        'on-primary-container': '#7384a9',
        'on-secondary-container': '#007235',
        'tertiary-container': '#251a00',
        'on-tertiary-container': '#a47f00',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#594400',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-dim': '#d2daf0',
        'outline': '#75777f',
        'outline-variant': '#c5c6cf',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      boxShadow: {
        card: '0 4px 20px -2px rgba(7, 27, 58, 0.06), 0 2px 6px -1px rgba(7, 27, 58, 0.04)',
        hover: '0 10px 25px -3px rgba(7, 27, 58, 0.1), 0 4px 10px -2px rgba(7, 27, 58, 0.05)',
      }
    },
  },
  plugins: [],
}
